/* Copyright (c) 2026 Dalsin Limited. OpenRTG, MIT licence (LICENSE).
 * SPDX-License-Identifier: MIT
 *
 * include/Warp3D/Warp3D.h's structures, byte for byte as 68k Warp3D programs
 * were compiled: every size and offset a program can see. Compiled (not
 * run) for the 68k by tests/run_3d.sh; a wrong number stops the build.
 * The numbers come from builds against the version 5 header programs used
 * (the 168 that version 4 shares are the same there), and the Team's header
 * matched all 185, and all 495 of version 5's constants, on 8 October 2026. */
#include <stddef.h>
#include <Warp3D/Warp3D.h>

#define CHECK(c) _Static_assert(c, #c)

CHECK(sizeof(W3D_Color) == 16);
CHECK(offsetof(W3D_Color, r) == 0);
CHECK(offsetof(W3D_Color, g) == 4);
CHECK(offsetof(W3D_Color, b) == 8);
CHECK(offsetof(W3D_Color, a) == 12);
CHECK(sizeof(W3D_Vertex) == 64);
CHECK(offsetof(W3D_Vertex, x) == 0);
CHECK(offsetof(W3D_Vertex, y) == 4);
CHECK(offsetof(W3D_Vertex, z) == 8);
CHECK(offsetof(W3D_Vertex, w) == 16);
CHECK(offsetof(W3D_Vertex, u) == 20);
CHECK(offsetof(W3D_Vertex, v) == 24);
CHECK(offsetof(W3D_Vertex, tex3d) == 28);
CHECK(offsetof(W3D_Vertex, color) == 32);
CHECK(offsetof(W3D_Vertex, spec) == 48);
CHECK(offsetof(W3D_Vertex, l) == 60);
CHECK(sizeof(W3D_Texture) == 146);
CHECK(offsetof(W3D_Texture, link) == 0);
CHECK(offsetof(W3D_Texture, resident) == 14);
CHECK(offsetof(W3D_Texture, mipmap) == 16);
CHECK(offsetof(W3D_Texture, dirty) == 18);
CHECK(offsetof(W3D_Texture, matchfmt) == 20);
CHECK(offsetof(W3D_Texture, pinned) == 22);
CHECK(offsetof(W3D_Texture, reserved2) == 24);
CHECK(offsetof(W3D_Texture, mipmapmask) == 26);
CHECK(offsetof(W3D_Texture, texsource) == 30);
CHECK(offsetof(W3D_Texture, mipmaps) == 34);
CHECK(offsetof(W3D_Texture, texfmtsrc) == 98);
CHECK(offsetof(W3D_Texture, palette) == 102);
CHECK(offsetof(W3D_Texture, texdata) == 106);
CHECK(offsetof(W3D_Texture, texdest) == 110);
CHECK(offsetof(W3D_Texture, texdestsize) == 114);
CHECK(offsetof(W3D_Texture, texwidth) == 118);
CHECK(offsetof(W3D_Texture, texwidthexp) == 122);
CHECK(offsetof(W3D_Texture, texheight) == 126);
CHECK(offsetof(W3D_Texture, texheightexp) == 130);
CHECK(offsetof(W3D_Texture, bytesperpix) == 134);
CHECK(offsetof(W3D_Texture, bytesperrow) == 138);
CHECK(offsetof(W3D_Texture, driver) == 142);
CHECK(sizeof(W3D_Point) == 72);
CHECK(offsetof(W3D_Point, v1) == 0);
CHECK(offsetof(W3D_Point, tex) == 64);
CHECK(offsetof(W3D_Point, pointsize) == 68);
CHECK(sizeof(W3D_Line) == 144);
CHECK(offsetof(W3D_Line, v1) == 0);
CHECK(offsetof(W3D_Line, v2) == 64);
CHECK(offsetof(W3D_Line, tex) == 128);
CHECK(offsetof(W3D_Line, linewidth) == 132);
CHECK(offsetof(W3D_Line, st_enable) == 136);
CHECK(offsetof(W3D_Line, st_pattern) == 138);
CHECK(offsetof(W3D_Line, st_factor) == 140);
CHECK(sizeof(W3D_Lines) == 24);
CHECK(offsetof(W3D_Lines, vertexcount) == 0);
CHECK(offsetof(W3D_Lines, v) == 4);
CHECK(offsetof(W3D_Lines, tex) == 8);
CHECK(offsetof(W3D_Lines, linewidth) == 12);
CHECK(offsetof(W3D_Lines, st_enable) == 16);
CHECK(offsetof(W3D_Lines, st_pattern) == 18);
CHECK(offsetof(W3D_Lines, st_factor) == 20);
CHECK(sizeof(W3D_Triangle) == 200);
CHECK(offsetof(W3D_Triangle, v1) == 0);
CHECK(offsetof(W3D_Triangle, v2) == 64);
CHECK(offsetof(W3D_Triangle, v3) == 128);
CHECK(offsetof(W3D_Triangle, tex) == 192);
CHECK(offsetof(W3D_Triangle, st_pattern) == 196);
CHECK(sizeof(W3D_TriangleV) == 20);
CHECK(offsetof(W3D_TriangleV, v1) == 0);
CHECK(offsetof(W3D_TriangleV, v2) == 4);
CHECK(offsetof(W3D_TriangleV, v3) == 8);
CHECK(offsetof(W3D_TriangleV, tex) == 12);
CHECK(offsetof(W3D_TriangleV, st_pattern) == 16);
CHECK(sizeof(W3D_Triangles) == 16);
CHECK(offsetof(W3D_Triangles, vertexcount) == 0);
CHECK(offsetof(W3D_Triangles, v) == 4);
CHECK(offsetof(W3D_Triangles, tex) == 8);
CHECK(offsetof(W3D_Triangles, st_pattern) == 12);
CHECK(sizeof(W3D_TrianglesV) == 16);
CHECK(offsetof(W3D_TrianglesV, vertexcount) == 0);
CHECK(offsetof(W3D_TrianglesV, v) == 4);
CHECK(offsetof(W3D_TrianglesV, tex) == 8);
CHECK(offsetof(W3D_TrianglesV, st_pattern) == 12);
CHECK(sizeof(W3D_Fog) == 24);
CHECK(offsetof(W3D_Fog, fog_start) == 0);
CHECK(offsetof(W3D_Fog, fog_end) == 4);
CHECK(offsetof(W3D_Fog, fog_density) == 8);
CHECK(offsetof(W3D_Fog, fog_color) == 12);
CHECK(sizeof(W3D_Scissor) == 16);
CHECK(offsetof(W3D_Scissor, left) == 0);
CHECK(offsetof(W3D_Scissor, top) == 4);
CHECK(offsetof(W3D_Scissor, width) == 8);
CHECK(offsetof(W3D_Scissor, height) == 12);
CHECK(sizeof(W3D_Context) == 712);
CHECK(offsetof(W3D_Context, driver) == 0);
CHECK(offsetof(W3D_Context, gfxdriver) == 4);
CHECK(offsetof(W3D_Context, drivertype) == 8);
CHECK(offsetof(W3D_Context, regbase) == 12);
CHECK(offsetof(W3D_Context, vmembase) == 16);
CHECK(offsetof(W3D_Context, zbuffer) == 20);
CHECK(offsetof(W3D_Context, stencilbuffer) == 24);
CHECK(offsetof(W3D_Context, state) == 28);
CHECK(offsetof(W3D_Context, drawregion) == 32);
CHECK(offsetof(W3D_Context, supportedfmt) == 36);
CHECK(offsetof(W3D_Context, format) == 40);
CHECK(offsetof(W3D_Context, yoffset) == 44);
CHECK(offsetof(W3D_Context, bprow) == 48);
CHECK(offsetof(W3D_Context, width) == 52);
CHECK(offsetof(W3D_Context, height) == 56);
CHECK(offsetof(W3D_Context, depth) == 60);
CHECK(offsetof(W3D_Context, chunky) == 64);
CHECK(offsetof(W3D_Context, destalpha) == 66);
CHECK(offsetof(W3D_Context, zbufferalloc) == 68);
CHECK(offsetof(W3D_Context, stbufferalloc) == 70);
CHECK(offsetof(W3D_Context, HWlocked) == 72);
CHECK(offsetof(W3D_Context, w3dbitmap) == 74);
CHECK(offsetof(W3D_Context, zbufferlost) == 76);
CHECK(offsetof(W3D_Context, reserved3) == 78);
CHECK(offsetof(W3D_Context, restex) == 80);
CHECK(offsetof(W3D_Context, tex) == 92);
CHECK(offsetof(W3D_Context, maxtexwidth) == 104);
CHECK(offsetof(W3D_Context, maxtexheight) == 108);
CHECK(offsetof(W3D_Context, maxtexwidthp) == 112);
CHECK(offsetof(W3D_Context, maxtexheightp) == 116);
CHECK(offsetof(W3D_Context, scissor) == 120);
CHECK(offsetof(W3D_Context, fog) == 136);
CHECK(offsetof(W3D_Context, envsupmask) == 160);
CHECK(offsetof(W3D_Context, queue) == 164);
CHECK(offsetof(W3D_Context, drawmem) == 168);
CHECK(offsetof(W3D_Context, globaltexenvmode) == 172);
CHECK(offsetof(W3D_Context, globaltexenvcolor) == 176);
CHECK(offsetof(W3D_Context, DriverBase) == 192);
CHECK(offsetof(W3D_Context, EnableMask) == 196);
CHECK(offsetof(W3D_Context, DisableMask) == 200);
CHECK(offsetof(W3D_Context, CurrentChip) == 204);
CHECK(offsetof(W3D_Context, DriverVersion) == 208);
CHECK(offsetof(W3D_Context, VertexPointer) == 212);
CHECK(offsetof(W3D_Context, VPStride) == 216);
CHECK(offsetof(W3D_Context, VPMode) == 220);
CHECK(offsetof(W3D_Context, VPFlags) == 224);
CHECK(offsetof(W3D_Context, TexCoordPointer) == 228);
CHECK(offsetof(W3D_Context, TPStride) == 292);
CHECK(offsetof(W3D_Context, CurrentTex) == 356);
CHECK(offsetof(W3D_Context, TPVOffs) == 420);
CHECK(offsetof(W3D_Context, TPWOffs) == 484);
CHECK(offsetof(W3D_Context, TPFlags) == 548);
CHECK(offsetof(W3D_Context, ColorPointer) == 612);
CHECK(offsetof(W3D_Context, CPStride) == 616);
CHECK(offsetof(W3D_Context, CPMode) == 620);
CHECK(offsetof(W3D_Context, CPFlags) == 624);
CHECK(offsetof(W3D_Context, FrontFaceOrder) == 628);
CHECK(offsetof(W3D_Context, specialbuffer) == 632);
CHECK(offsetof(W3D_Context, SecondaryColorPointer) == 636);
CHECK(offsetof(W3D_Context, SCPStride) == 640);
CHECK(offsetof(W3D_Context, SCPMode) == 644);
CHECK(offsetof(W3D_Context, SCPFlags) == 648);
CHECK(offsetof(W3D_Context, FogCoordPointer) == 652);
CHECK(offsetof(W3D_Context, FCPMode) == 656);
CHECK(offsetof(W3D_Context, FCPStride) == 660);
CHECK(offsetof(W3D_Context, FCPFlags) == 664);
CHECK(offsetof(W3D_Context, orig_drawregion) == 668);
CHECK(offsetof(W3D_Context, orig_zbuffer) == 672);
CHECK(offsetof(W3D_Context, orig_stencilbuffer) == 676);
CHECK(offsetof(W3D_Context, orig_width) == 680);
CHECK(offsetof(W3D_Context, orig_height) == 684);
CHECK(offsetof(W3D_Context, orig_yoffset) == 688);
CHECK(offsetof(W3D_Context, orig_scissor) == 692);
CHECK(offsetof(W3D_Context, orig_bprow) == 708);
CHECK(sizeof(W3D_Bitmap) == 20);
CHECK(offsetof(W3D_Bitmap, bprow) == 0);
CHECK(offsetof(W3D_Bitmap, width) == 4);
CHECK(offsetof(W3D_Bitmap, height) == 8);
CHECK(offsetof(W3D_Bitmap, format) == 12);
CHECK(offsetof(W3D_Bitmap, dest) == 16);
CHECK(sizeof(W3D_Driver) == 14);
CHECK(offsetof(W3D_Driver, ChipID) == 0);
CHECK(offsetof(W3D_Driver, formats) == 4);
CHECK(offsetof(W3D_Driver, name) == 8);
CHECK(offsetof(W3D_Driver, swdriver) == 12);
CHECK(sizeof(W3D_ScreenMode) == 56);
CHECK(offsetof(W3D_ScreenMode, ModeID) == 0);
CHECK(offsetof(W3D_ScreenMode, Width) == 4);
CHECK(offsetof(W3D_ScreenMode, Height) == 8);
CHECK(offsetof(W3D_ScreenMode, Depth) == 12);
CHECK(offsetof(W3D_ScreenMode, DisplayName) == 16);
CHECK(offsetof(W3D_ScreenMode, Driver) == 48);
CHECK(offsetof(W3D_ScreenMode, Next) == 52);

/* A few numbers programs test most, as a second guard. */
CHECK(W3D_CC_BITMAP == 0x80200000UL);
CHECK(W3D_ATO_MIPMAPPTRS == 0x80201006UL);
CHECK(W3D_STB_TAGS == 0x80204000UL);
CHECK(W3D_FMT_A8R8G8B8 == 0x800);
CHECK(W3D_ZBUFFER == 0x800);
CHECK(W3D_Q_NUM_TMU == 170);
CHECK(W3D_VFORMAT_FOG_FACTOR == 0x200000);
CHECK(W3D_UNSUPPORTED == -30);
