#!/bin/sh
# Copyright (c) 2026 Dalsin Limited. OpenRTG, MIT licence (LICENSE).
# SPDX-License-Identifier: MIT
# Compiles ogpu.comp into ogpu_vk_spv.h (SPIR-V as a C array), which is kept
# in the repository so building the back end needs no shader compiler.
#   host/vulkan/build_spv.sh        (needs glslangValidator: glslang-tools)
set -eu
HERE=$(cd "$(dirname "$0")" && pwd)
glslangValidator -V --target-env vulkan1.1 --vn ogpu_comp_spv -o "$HERE/ogpu_vk_spv.h.tmp" "$HERE/ogpu.comp" >/dev/null
{
    echo "/* Generated by host/vulkan/build_spv.sh from ogpu.comp: do not edit. */"
    cat "$HERE/ogpu_vk_spv.h.tmp"
} > "$HERE/ogpu_vk_spv.h"
rm -f "$HERE/ogpu_vk_spv.h.tmp"
