#!/usr/bin/env python3
# Copyright (c) 2026 Dalsin Limited. OpenRTG, MIT licence (LICENSE).
# SPDX-License-Identifier: MIT
"""GL.module's two generated halves, from one list of names.

  gen_gl.py --stub gl_stub_calls.s --exports gl_exports.c
            [--xml MESA_GLAPI_GEN_DIR] [--header GLA_HEADER]... NAMES...

NAMES are files with one call per line: the GL entry points Mesa's glapi
generated for this build (library/modules/gl/module/build.sh lists them from
libglapi_bridge.a) and stubs/gl/gla.names.

gl_stub_calls.s, for libGL.a: one entry per call, sorted by name. GL.module
is shared (built -fbaserel32: its code loaded once, each program's data its
own; include/opengpu/module.h), so a call must run with A4 on this program's
copy of the module's data and give the program its own A4 back. Each entry
puts its slot in gl_stub_table into A0 and the size of its arguments in D0
(in longs) and goes to gl_stub_call, which loads the module on the first
call (gl_stub.c), saves A4, copies the arguments, sets the module's A4,
calls, and puts A4 back. Results come back as they are (D0, D1, FP0).
The argument sizes come from Mesa's glapi XML (--xml) for GL, and from the
GLA headers (--header) for GLA: a GLdouble or 64-bit integer is two longs,
anything else one. A call found in neither copies FALLBACK longs, which is
more than any GL call has (reading a little more of the caller's stack does
no harm).

gla_get_proc_address is gl_stub.c's, not an entry: what the module
answers is turned into this stub's own entry for that name, so calls through
it set A4 too; a name the stub doesn't know gives NULL.

gl_exports.c, for GL.module: the same names with the module's functions, the
table GLModuleTable hands out (stubs/gl/gl_module.h).
"""
import argparse
import glob
import os
import re
import sys
import xml.etree.ElementTree as ET

NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
TWO_LONGS = {"GLdouble", "GLclampd", "GLint64", "GLuint64", "GLint64EXT", "GLuint64EXT", "double",
             "int64_t", "uint64_t", "long long", "unsigned long long"}
FALLBACK = 24
SPECIAL = {"gla_get_proc_address": "_gla_get_proc_address"}   # gl_stub.c


def size_of(t):
    t = t.replace("const", "").strip()
    if "*" in t:
        return 1
    return 2 if t in TWO_LONGS else 1


def xml_sizes(d):
    """{glName: longs} from Mesa's glapi XML (padding parameters aren't C ones)."""
    out = {}
    for f in sorted(glob.glob(os.path.join(d, "*.xml"))):
        try:
            tree = ET.parse(f)
        except ET.ParseError:
            continue
        for fn in tree.iter("function"):
            n = sum(size_of(p.get("type", "")) for p in fn.iter("param") if p.get("padding") != "true")
            out.setdefault("gl" + fn.get("name"), n)
    return out


def header_sizes(paths):
    """{name: longs} from C prototypes in headers (the GLA calls)."""
    out = {}
    for f in paths:
        text = re.sub(r"/\*.*?\*/", " ", open(f).read(), flags=re.S)
        for m in re.finditer(r"\b(gla_[A-Za-z0-9_]+)\s*\(([^)]*)\)\s*;", text):
            args = " ".join(m.group(2).split())
            if args in ("", "void"):
                n = 0
            else:
                n = 0
                for a in args.split(","):
                    a = re.sub(r"\b[A-Za-z_][A-Za-z0-9_]*\s*$", "", a.strip()) if "*" not in a.split()[-1] else a
                    n += size_of(a.strip())
            out[m.group(1)] = n
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stub", required=True)
    ap.add_argument("--exports", required=True)
    ap.add_argument("--xml")
    ap.add_argument("--header", action="append", default=[])
    ap.add_argument("names", nargs="+")
    a = ap.parse_args()
    names = set()
    for f in a.names:
        for line in open(f):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if not NAME.match(line):
                sys.exit("gen_gl: not a name in %s: %r" % (f, line))
            names.add(line)
    names = sorted(names)   # strcmp order: the names are ASCII
    n = len(names)
    sizes = xml_sizes(a.xml) if a.xml else {}
    sizes.update(header_sizes(a.header))
    unknown = [nm for nm in names if nm not in sizes]
    longs = [sizes.get(nm, FALLBACK) for nm in names]

    with open(a.stub, "w") as s:
        s.write("| Generated by stubs/gl/gen_gl.py for libGL.a: do not edit.\n")
        s.write("| %d calls, sorted by name; each sets A4 for its slot in gl_stub_table (gl_stub_call).\n\n" % n)
        s.write("\t.text\n")
        for i, nm in enumerate(names):
            if nm in SPECIAL:
                continue
            s.write("\t.globl\t_%s\n_%s:\n\tlea\t_gl_stub_table+%d,%%a0\n\tmoveq\t#%d,%%d0\n\tbra.w\t_gl_stub_call\n"
                    % (nm, nm, 4 * i, longs[i]))
        s.write("""
| A0: the call's slot; D0: its arguments, in longs. The first call into GL
| loads the module (gl_stub_load in gl_stub.c). Then: the program's A4 and A5
| saved, the arguments copied below them, the module's A4 set, the call, and
| the program's registers back. D0-D1/A0-A1 are the caller's to lose, and
| the result in D0, D1 or FP0 comes back untouched.
\t.globl\t_gl_stub_call
_gl_stub_call:
\ttst.l\t_gl_stub_module
\tbne.s\t1f
\tmovem.l\t%d0/%a0,-(%sp)
\tjsr\t_gl_stub_load
\tmovem.l\t(%sp)+,%d0/%a0
1:\tmove.l\t%a4,-(%sp)
\tlink\t%a5,#0
\tlea\t12(%a5,%d0.l*4),%a1
\tbra.s\t3f
2:\tmove.l\t-(%a1),-(%sp)
3:\tdbra\t%d0,2b
\tmove.l\t_gl_stub_a4,%a4
\tmove.l\t(%a0),%a1
\tjsr\t(%a1)
\tunlk\t%a5
\tmove.l\t(%sp)+,%a4
\trts

| A call this GL.module doesn't have: 0.
\t.globl\t_gl_stub_missing
_gl_stub_missing:
\tmoveq\t#0,%d0
\trts

\t.data
\t.globl\t_gl_stub_table
_gl_stub_table:
""")
        for i in range(n):
            s.write("\t.long\t_gl_stub_missing\n")
        s.write("\t.globl\t_gl_stub_count\n_gl_stub_count:\n\t.long\t%d\n" % n)
        s.write("\t.globl\t_gl_stub_entries\n_gl_stub_entries:\n")
        for nm in names:
            s.write("\t.long\t%s\n" % SPECIAL.get(nm, "_" + nm))
        s.write("\t.globl\t_gl_stub_names\n_gl_stub_names:\n")
        for i in range(n):
            s.write("\t.long\t.Lname%d\n" % i)
        for i, nm in enumerate(names):
            s.write(".Lname%d:\t.asciz\t\"%s\"\n" % (i, nm))

    with open(a.exports, "w") as c:
        c.write("/* Generated by stubs/gl/gen_gl.py for GL.module: do not edit. */\n")
        c.write("#include <opengpu/module.h>\n\n")
        for nm in names:
            c.write("extern void %s(void);\n" % nm)
        c.write("\nconst struct OGPUModuleExport gl_module_exports[%d] = {\n" % n)
        for nm in names:
            c.write("    { \"%s\", (APTR)%s },\n" % (nm, nm))
        c.write("};\nconst ULONG gl_module_export_count = %d;\n" % n)
    print("gen_gl: %d calls, arguments up to %d longs%s" % (
        n, max(sizes.get(nm, 0) for nm in names) if names else 0,
        "; %d with no known arguments copy %d longs (%s)" % (len(unknown), FALLBACK, " ".join(unknown[:8]) + (" ..." if len(unknown) > 8 else "")) if unknown else ""))


if __name__ == "__main__":
    main()
