#!/usr/bin/env python3
# Copyright (c) 2026 Dalsin Limited. OpenRTG, MIT licence (LICENSE).
# SPDX-License-Identifier: MIT
"""GL.module's two generated halves, from one list of names.

  gen_gl.py --stub gl_stub_calls.s --exports gl_exports.c NAMES...

NAMES are files with one call per line: the GL entry points Mesa's glapi
generated for this build (library/modules/gl/module/build.sh lists them from
libglapi_bridge.a) and stubs/gl/gla.names.

gl_stub_calls.s, for libGL.a: one entry per call, sorted by name. Each jumps
through its slot in gl_stub_table, which starts out pointing at
gl_stub_first; the first call binds the whole table (gl_stub.c) and goes on.
The entries touch only A0 and pass the stack as it is, so every call works
whatever its arguments, varargs included.

gl_exports.c, for GL.module: the same names with the module's functions, the
table GLModuleTable hands out (stubs/gl/gl_module.h).
"""
import argparse
import re
import sys

NAME = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stub", required=True)
    ap.add_argument("--exports", required=True)
    ap.add_argument("names", nargs="+")
    a = ap.parse_args()
    names = set()
    for f in a.names:
        for line in open(f):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if not NAME.match(line):
                sys.exit("gen_gl: not a name in %s: %r" % (f, line))
            names.add(line)
    names = sorted(names)   # strcmp order: the names are ASCII
    n = len(names)

    with open(a.stub, "w") as s:
        s.write("| Generated by stubs/gl/gen_gl.py for libGL.a: do not edit.\n")
        s.write("| %d calls, sorted by name; each jumps through its slot in gl_stub_table.\n\n" % n)
        s.write("\t.text\n")
        for i, nm in enumerate(names):
            s.write("\t.globl\t_%s\n_%s:\n\tlea\t_gl_stub_table+%d,%%a0\n\tmove.l\t(%%a0),-(%%sp)\n\trts\n" % (nm, nm, 4 * i))
        s.write("""
| The first call into GL: bind the table (gl_stub.c), then make the call.
\t.globl\t_gl_stub_first
_gl_stub_first:
\tmove.l\t%a0,-(%sp)
\tjsr\t_gl_stub_load
\tmove.l\t(%sp)+,%a0
\tmove.l\t(%a0),-(%sp)
\trts

| A call this GL.module doesn't have: 0.
\t.globl\t_gl_stub_missing
_gl_stub_missing:
\tmoveq\t#0,%d0
\trts

\t.data
\t.globl\t_gl_stub_table
_gl_stub_table:
""")
        for i in range(n):
            s.write("\t.long\t_gl_stub_first\n")
        s.write("\t.globl\t_gl_stub_count\n_gl_stub_count:\n\t.long\t%d\n" % n)
        s.write("\t.globl\t_gl_stub_names\n_gl_stub_names:\n")
        for i in range(n):
            s.write("\t.long\t.Lname%d\n" % i)
        for i, nm in enumerate(names):
            s.write(".Lname%d:\t.asciz\t\"%s\"\n" % (i, nm))

    with open(a.exports, "w") as c:
        c.write("/* Generated by stubs/gl/gen_gl.py for GL.module: do not edit. */\n")
        c.write("#include <opengpu/module.h>\n\n")
        for nm in names:
            c.write("extern void %s(void);\n" % nm)
        c.write("\nconst struct OGPUModuleExport gl_module_exports[%d] = {\n" % n)
        for nm in names:
            c.write("    { \"%s\", (APTR)%s },\n" % (nm, nm))
        c.write("};\nconst ULONG gl_module_export_count = %d;\n" % n)
    print("gen_gl: %d calls" % n)


if __name__ == "__main__":
    main()
