/* Copyright (c) 2026 Dalsin Limited. OpenRTG, MIT licence (LICENSE).
 * SPDX-License-Identifier: MIT
 *
 * libGL.a: GL and GLES for programs on AmigaOS 3.2, from OpenGPU's
 * GL.module. Programs include Mesa's GL headers and gla_core.h as before,
 * and link -lGL in place of Mesa itself (about 20 MB).
 *
 * gl_stub_calls.s (generated by gen_gl.py) has an entry for every call. The
 * first call into GL lands in gl_stub_load, which loads GL.module through
 * opengpu.library's OGPU_ModuleOpen (LoadSeg itself on an opengpu.library
 * older than 0.5) and binds every entry to the module's function of the same
 * name. From then on a call is three instructions and a jump.
 *
 * Each program gets its own copy of the module (the layout's step 1), so
 * Mesa's globals are its own. GL runs on the program's stack: give main
 * a big one (OpenDemos asks libnix for 1 MB). */
#include <exec/types.h>
#include <dos/dos.h>
#include <proto/exec.h>
#include <proto/dos.h>
#include <stdlib.h>
#include <string.h>

#include "gl_module.h"

/* opengpu.library's calls through the stub's own base, so a program's
 * OpenGPUBase is left alone. */
#define OPENGPU_BASE_NAME gl_stub_OpenGPUBase
#include <inline/opengpu.h>
static struct Library *gl_stub_OpenGPUBase;

/* gl_stub_calls.s */
extern APTR gl_stub_table[];
extern const char *const gl_stub_names[];
extern const ULONG gl_stub_count;
extern void gl_stub_missing(void);

static APTR handle;
static BPTR seg;
static struct GLModuleTable *module;

static void fail(const char *why)
{
    BPTR out = Output();
    if (out) {
        FPuts(out, (CONST_STRPTR) "GL: ");
        FPuts(out, (CONST_STRPTR)why);
        FPuts(out, (CONST_STRPTR) "\n");
    }
    exit(20);
}

/* Called by gl_stub_first, from the program's first GL call. */
void gl_stub_load(void)
{
    ULONG i = 0, j = 0;
    if (module) return;
    gl_stub_OpenGPUBase = OpenLibrary((CONST_STRPTR) "opengpu.library", 0);
    if (gl_stub_OpenGPUBase && (gl_stub_OpenGPUBase->lib_Version > 0 ||
                                gl_stub_OpenGPUBase->lib_Revision >= OGPU_MODULE_LIB_REVISION)) {
        handle = OGPU_ModuleOpen((CONST_STRPTR)GL_MODULE_NAME, GL_MODULE_VERSION, (APTR *)&module);
        if (!handle && IoErr() == ERROR_OBJECT_NOT_FOUND)
            fail("this program needs " GL_MODULE_FILE " (OpenGPU), which isn't installed.");
    } else if ((seg = LoadSeg((CONST_STRPTR)GL_MODULE_FILE)) != 0) {
        struct OGPUModuleArgs args;
        args.SysBase = SysBase;
        args.DOSBase = (struct Library *)DOSBase;
        args.OpenGPUBase = gl_stub_OpenGPUBase;
        args.version = GL_MODULE_VERSION;
        module = (struct GLModuleTable *)OGPU_MODULE_ENTRY(seg)(&args);
    } else
        fail("this program needs " GL_MODULE_FILE " (OpenGPU), which isn't installed.");
    if (!module)
        fail(GL_MODULE_FILE " is older than this program, or couldn't start (memory?).");
    /* Both lists are sorted: one pass binds them. */
    while (i < gl_stub_count) {
        int c = j < module->count ? strcmp(gl_stub_names[i], module->exports[j].name) : -1;
        if (c == 0)
            gl_stub_table[i++] = module->exports[j++].func;
        else if (c < 0)
            gl_stub_table[i++] = (APTR)gl_stub_missing;
        else
            j++;
    }
}

static void __attribute__((destructor)) gl_stub_close(void)
{
    if (module) module->close();
    module = NULL;
    if (handle) OGPU_ModuleClose(handle);
    handle = NULL;
    if (seg) UnLoadSeg(seg);
    seg = 0;
    if (gl_stub_OpenGPUBase) CloseLibrary(gl_stub_OpenGPUBase);
    gl_stub_OpenGPUBase = NULL;
}
